.\" $Id: bluewho.1 0.1 2010-01-02 02:38 muflone $
.\"
.\" Copyright (c) 2009 Fabio Castelli

.TH BLUEWHO "1" "January 02, 2010"

.SH NAME
.B BlueWho
\- Information and notification of new discovered bluetooth devices

.SH SYNOPSIS
bluewho

.SH DESCRIPTION
.PP
.B BlueWho
is a GTK utility to inform and notify you when a new bluetooth device is 
discovered.

.PP
Detection can be requested by the user or automatically continuous until is
stopped. A visible and audible notification can be fired whenever a new
device is detected.

.PP
Each device found will be saved on the list as well its name, MAC address,
last seen date and time.
For each device a list of available Bluetooth services can be requested.

.SH FILES
Program user's configuration and detected devices list will be kept under
~/.config/bluewho/

.SH AUTHORS
.B BlueWho
was written by Fabio Castelli <muflone@vbsimple.net>

.SH HOMEPAGE
International project: http://code.google.com/p/bluewho/

Italian project: http://ubuntrucchi.wordpress.com/progetti-projects/bluewho/

