.\" $Id: bluewho.1 0.1 2021-04-25 15:58 muflone $
.\"
.\" Copyright (c) 2009-2021 Fabio Castelli

.TH BLUEWHO "1" "April 25, 2021"

.SH NAME
.B BlueWho
\- Information and notification of new discovered bluetooth devices

.SH SYNOPSIS
bluewho

.SH DESCRIPTION
.PP
.B BlueWho
is a GTK utility to inform and notify you when a new bluetooth device is 
discovered.

.PP
Detection can be requested by the user or automatically continuous until is
stopped. A visible and audible notification can be fired whenever a new
device is detected.

.PP
Each device found will be saved on the list as well its name, MAC address,
last seen date and time.
For each device a list of available Bluetooth services can be requested.

.SH FILES
Program user's configuration and detected devices list will be kept under
~/.config/bluewho/

.SH REPORTING BUGS
Report bugs to https://github.com/muflone/bluewho/issues

.SH AUTHORS
.B BlueWho
was written by Fabio Castelli (Muflone) <muflone@vbsimple.net>

.SH HOMEPAGE
Home page: http://www.muflone.com/bluewho

Source code: https://github.com/muflone/bluewho/

.SH COPYRIGHT
Copyright © 2009-2021 Fabio Castelli.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/gpl-2.0.html>.

This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
