.\" $Id: bluewho.1 2022-04-18 18:33 muflone $
.\"
.\" Copyright (c) 2009-2022 Fabio Castelli

.TH BLUEWHO "1" "April 18, 2022"

.SH NAME
.B BlueWho
\- Information and notification of new discovered bluetooth devices

.SH SYNOPSIS
bluewho

.SH DESCRIPTION
.PP
.B BlueWho
is a GTK utility to inform and notify you when a new bluetooth device is 
discovered.

.PP
Detection can be requested by the user or automatically continuous until is
stopped. A visible and audible notification can be fired whenever a new
device is detected.

.PP
Each device found will be saved on the list as well its name, MAC address,
last seen date and time.
For each device a list of available Bluetooth services can be requested.

.SH FILES
Program user's configuration and detected devices list will be kept under
~/.config/bluewho/

.SH REPORTING BUGS
Report bugs to https://github.com/muflone/bluewho/issues

.SH AUTHORS
.B BlueWho
was written by Fabio Castelli (Muflone) <muflone@muflone.com>

.SH HOMEPAGE
Home page: https://www.muflone.com/bluewho

Source code: https://github.com/muflone/bluewho/

.SH COPYRIGHT
Copyright © 2009-2022 Fabio Castelli.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl-3.0.html>.

This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
